### ISSUE TITLE
pip install PSphinxTheme Error.

### ISSUE THREAD

**Issue by sotex** [sphinx-themes/sphinx-themes.org#13]
I can't install on windows.
```bash
pip install PSphinxTheme
Collecting PSphinxTheme
  Using cached https://files.pythonhosted.org/packages/9c/c3/ef591d625532110a7ca544cc24e89422242836247f24da75f94f85d46dd7/PSphinxTheme-2.0.5.tar.bz2
    ERROR: Command errored out with exit status 1:
     command: 'C:\scoop\apps\miniconda3\4.7.12.1\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\o\\AppData\\Local\\Temp\\pip-install-p5lu_16l\\PSphinxTheme\\setup.py'"'"'; __file__='"'"'C:\\Users\\o\\AppData\\Local\\Temp\\pip-install-p5lu_16l\\PSphinxTheme\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\o\AppData\Local\Temp\pip-install-p5lu_16l\PSphinxTheme\pip-egg-info'
         cwd: C:\Users\o\AppData\Local\Temp\pip-install-p5lu_16l\PSphinxTheme\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\o\AppData\Local\Temp\pip-install-p5lu_16l\PSphinxTheme\setup.py", line 62, in <module>
        '''.format(sys_version_info[:2][0], sys_version_info[:2][1], TESTED_HOST_OS))
    IndexError: tuple index out of range
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

![图片](https://user-images.githubusercontent.com/16911453/79765848-bfb72400-8359-11ea-8103-8381c3da31a0.png)

**Comment by shirou** [comment]
please open an issue at that theme repository.
